### ISSUE TITLE
falsches Repo

### ISSUE THREAD

**Issue by hollesse** [darkson95/setlXBotDocker#1]
Hey,
du hast doch dein Repo umbenannt, welches in der Dockerfile via git geklont werden soll. Damit musst du doch auch hier in Dockerfile den Namen ändern.

**Comment by darkson95** [comment]
Hi,
danke für die Info! Ich will aber den setlX-Bot mit C# programmieren, da ich da mehr Möglichkeiten habe. Der aktuelle Bot ist sehr instabil und wird nicht mehr weiter entwickelt. Ich lasse die Repo noch online, bis die neue Version öffentlich wird.
